### ISSUE TITLE
Issues with sonar-java-plugin, SQL Server setup, image tag

### ISSUE THREAD

**Issue by riserrad** [EddEdw/sonarqube-azure-setup#1]
## Source for sonar-java-plugin

Inside the Dockerfile, it is set to:

`https://sonarsource.bintray.com/Distribution/sonar-java-plugin/sonar-java-plugin-${SONAR_JAVA_VERSION}.jar`

But now it is

`https://dl.bintray.com/sonarsource/SonarQube/org/sonarsource/java/sonar-java-plugin/${SONAR_JAVA_VERSION}/sonar-java-plugin-${SONAR_JAVA_VERSION}.jar`

Source:

https://dl.bintray.com/sonarsource/SonarQube/org/sonarsource/java/sonar-java-plugin/

## config connection-string now requires type

`az webapp config connection-string` now requires `--connection-string-type`. For this sample, the following needs to be added:

`--connection-string-type SQLAzure`

## Docker Image tag

As we're setting the image tag here:

`docker build -t $CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG .`

It makes sense to use it while creating the app & configuring which image to use, like this:

`--deployment-container-image-name $CONTAINER_REGISTRY_FQDN/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG`
`--docker-custom-image-name $CONTAINER_REGISTRY_FQDN/$CONTAINER_IMAGE_NAME:$CONTAINER_IMAGE_TAG`

**Comment by Hupka** [comment]
Hey @ricardoserradas,

thank you for the feedback, read it & understood. Since you provided the fix via pull request already, I close this issue.
